version: '3'
services:
  solr:
    image: solr:latest
    container_name: n11_solr
    ports:
      - "127.0.0.1:8983:8983"
    volumes:
      - ./data:/var/solr
    command:
      - solr-precreate
      - n11-restaurants